### PR TITLE
load not auto-loadable class question_bank - Moodle 4.1

### PR DESCRIPTION
**Pull request by christianabila**
Had this error when trying to add either a purpose or category in the data registry (`admin/tool/dataprivacy/dataregistry.php`)

Loading the class file fixes this issue.

Discovered with @phager-at

### CODE REVIEW

**Comment by christianabila** [comment]
Alternatively, `require_once($CFG->libdir . '/questionlib.php');` seems to do the trick to.

**Comment by srobotta** [comment]
I cannot reproduce the error to actually check what the fix should be. I had a similar error reported in Moodle 4.1 and therefore, did a fix in the latest master. I guess that might solve your problem as well.

**Comment by christianabila** [comment]
> I cannot reproduce the error to actually check what the fix should be. I had a similar error reported in Moodle 4.1 and therefore, did a fix in the latest master. I guess that might solve your problem as well.

Sorry, my bug report was incomplete...the error occurred in Moodle 4.1.

I have just checked out v1.10 and in works fine now.

**Comment by srobotta** [comment]
Thank you for your feedback. Then I will close this pull request. And thanks for taking the effort on reporting and actually creating a pull request.

**Pull request closed without merging**
